import os

DBT_PROJECT_NAME = os.getenv("DBT_PROJECT_NAME", "")
DBT_PROJECT_DIR = DBT_PROJECT_NAME
DBT_PROFILES_DIR = f"{DBT_PROJECT_DIR}/config"

DBT_DATABASE_NAME = os.getenv("DBT_DATABASE_NAME", "dicom.duckdb")
DBT_DATABASE_PATH = os.path.join(DBT_PROJECT_DIR, DBT_DATABASE_NAME)
